// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v5.29.1
// source: proto/basic/enum.proto

package basic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DbBool int32

const (
	DbBool_DbBool_False DbBool = 0
	DbBool_DbBool_True  DbBool = 1
)

// Enum value maps for DbBool.
var (
	DbBool_name = map[int32]string{
		0: "DbBool_False",
		1: "DbBool_True",
	}
	DbBool_value = map[string]int32{
		"DbBool_False": 0,
		"DbBool_True":  1,
	}
)

func (x DbBool) Enum() *DbBool {
	p := new(DbBool)
	*p = x
	return p
}

func (x DbBool) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DbBool) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_basic_enum_proto_enumTypes[0].Descriptor()
}

func (DbBool) Type() protoreflect.EnumType {
	return &file_proto_basic_enum_proto_enumTypes[0]
}

func (x DbBool) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DbBool.Descriptor instead.
func (DbBool) EnumDescriptor() ([]byte, []int) {
	return file_proto_basic_enum_proto_rawDescGZIP(), []int{0}
}

type DateSpan int32

const (
	DateSpan_DateSpan_Day   DateSpan = 0
	DateSpan_DateSpan_Weak  DateSpan = 1
	DateSpan_DateSpan_Month DateSpan = 2
	DateSpan_DateSpan_Year  DateSpan = 3
)

// Enum value maps for DateSpan.
var (
	DateSpan_name = map[int32]string{
		0: "DateSpan_Day",
		1: "DateSpan_Weak",
		2: "DateSpan_Month",
		3: "DateSpan_Year",
	}
	DateSpan_value = map[string]int32{
		"DateSpan_Day":   0,
		"DateSpan_Weak":  1,
		"DateSpan_Month": 2,
		"DateSpan_Year":  3,
	}
)

func (x DateSpan) Enum() *DateSpan {
	p := new(DateSpan)
	*p = x
	return p
}

func (x DateSpan) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DateSpan) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_basic_enum_proto_enumTypes[1].Descriptor()
}

func (DateSpan) Type() protoreflect.EnumType {
	return &file_proto_basic_enum_proto_enumTypes[1]
}

func (x DateSpan) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DateSpan.Descriptor instead.
func (DateSpan) EnumDescriptor() ([]byte, []int) {
	return file_proto_basic_enum_proto_rawDescGZIP(), []int{1}
}

type CombineKind int32

const (
	CombineKind_CombineKind_Union     CombineKind = 0 //并集
	CombineKind_CombineKind_Except    CombineKind = 1 //差集
	CombineKind_CombineKind_Intersect CombineKind = 2 //交集
)

// Enum value maps for CombineKind.
var (
	CombineKind_name = map[int32]string{
		0: "CombineKind_Union",
		1: "CombineKind_Except",
		2: "CombineKind_Intersect",
	}
	CombineKind_value = map[string]int32{
		"CombineKind_Union":     0,
		"CombineKind_Except":    1,
		"CombineKind_Intersect": 2,
	}
)

func (x CombineKind) Enum() *CombineKind {
	p := new(CombineKind)
	*p = x
	return p
}

func (x CombineKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CombineKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_basic_enum_proto_enumTypes[2].Descriptor()
}

func (CombineKind) Type() protoreflect.EnumType {
	return &file_proto_basic_enum_proto_enumTypes[2]
}

func (x CombineKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CombineKind.Descriptor instead.
func (CombineKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_basic_enum_proto_rawDescGZIP(), []int{2}
}

type Language int32

const (
	// 自动
	Language_Language_auto Language = 0
	// 简体中文
	Language_Language_zhCN Language = 1
	// 繁体中文
	Language_Language_zhTW Language = 2
	// 英语
	Language_Language_enUS Language = 3
	// 法语
	Language_Language_frFR Language = 4
	// 德语
	Language_Language_deDE Language = 5
	// 日本语
	Language_Language_jaJP Language = 6
	// 西班牙语
	Language_Language_esES Language = 7
	// 葡萄牙语
	Language_Language_ptBR Language = 8
	// 意大利语
	Language_Language_itIT Language = 9
	// 荷兰语
	Language_Language_nlNL Language = 10
	// 土耳其语
	Language_Language_trTR Language = 11
	// 俄语
	Language_Language_ruRU Language = 12
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0:  "Language_auto",
		1:  "Language_zhCN",
		2:  "Language_zhTW",
		3:  "Language_enUS",
		4:  "Language_frFR",
		5:  "Language_deDE",
		6:  "Language_jaJP",
		7:  "Language_esES",
		8:  "Language_ptBR",
		9:  "Language_itIT",
		10: "Language_nlNL",
		11: "Language_trTR",
		12: "Language_ruRU",
	}
	Language_value = map[string]int32{
		"Language_auto": 0,
		"Language_zhCN": 1,
		"Language_zhTW": 2,
		"Language_enUS": 3,
		"Language_frFR": 4,
		"Language_deDE": 5,
		"Language_jaJP": 6,
		"Language_esES": 7,
		"Language_ptBR": 8,
		"Language_itIT": 9,
		"Language_nlNL": 10,
		"Language_trTR": 11,
		"Language_ruRU": 12,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_basic_enum_proto_enumTypes[3].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_proto_basic_enum_proto_enumTypes[3]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_proto_basic_enum_proto_rawDescGZIP(), []int{3}
}

var File_proto_basic_enum_proto protoreflect.FileDescriptor

var file_proto_basic_enum_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x65, 0x6e,
	0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2a,
	0x2b, 0x0a, 0x06, 0x44, 0x62, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x62, 0x42,
	0x6f, 0x6f, 0x6c, 0x5f, 0x46, 0x61, 0x6c, 0x73, 0x65, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x44,
	0x62, 0x42, 0x6f, 0x6f, 0x6c, 0x5f, 0x54, 0x72, 0x75, 0x65, 0x10, 0x01, 0x2a, 0x56, 0x0a, 0x08,
	0x44, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x6e, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x65,
	0x53, 0x70, 0x61, 0x6e, 0x5f, 0x44, 0x61, 0x79, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x44, 0x61,
	0x74, 0x65, 0x53, 0x70, 0x61, 0x6e, 0x5f, 0x57, 0x65, 0x61, 0x6b, 0x10, 0x01, 0x12, 0x12, 0x0a,
	0x0e, 0x44, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x6e, 0x5f, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x10,
	0x02, 0x12, 0x11, 0x0a, 0x0d, 0x44, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x6e, 0x5f, 0x59, 0x65,
	0x61, 0x72, 0x10, 0x03, 0x2a, 0x57, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x65, 0x4b,
	0x69, 0x6e, 0x64, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x65, 0x4b, 0x69,
	0x6e, 0x64, 0x5f, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x6f,
	0x6d, 0x62, 0x69, 0x6e, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x5f, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74,
	0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x65, 0x4b, 0x69, 0x6e,
	0x64, 0x5f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x63, 0x74, 0x10, 0x02, 0x2a, 0x81, 0x02,
	0x0a, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x61, 0x75, 0x74, 0x6f, 0x10, 0x00, 0x12, 0x11, 0x0a,
	0x0d, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x7a, 0x68, 0x43, 0x4e, 0x10, 0x01,
	0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x7a, 0x68, 0x54,
	0x57, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x5f,
	0x65, 0x6e, 0x55, 0x53, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x5f, 0x66, 0x72, 0x46, 0x52, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x64, 0x65, 0x44, 0x45, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d,
	0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x6a, 0x61, 0x4a, 0x50, 0x10, 0x06, 0x12,
	0x11, 0x0a, 0x0d, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x65, 0x73, 0x45, 0x53,
	0x10, 0x07, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x70,
	0x74, 0x42, 0x52, 0x10, 0x08, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x5f, 0x69, 0x74, 0x49, 0x54, 0x10, 0x09, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x6c, 0x4e, 0x4c, 0x10, 0x0a, 0x12, 0x11, 0x0a, 0x0d, 0x4c,
	0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x72, 0x54, 0x52, 0x10, 0x0b, 0x12, 0x11,
	0x0a, 0x0d, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x75, 0x52, 0x55, 0x10,
	0x0c, 0x42, 0x23, 0x5a, 0x0f, 0x62, 0x73, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62,
	0x61, 0x73, 0x69, 0x63, 0xaa, 0x02, 0x0f, 0x42, 0x53, 0x49, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_basic_enum_proto_rawDescOnce sync.Once
	file_proto_basic_enum_proto_rawDescData = file_proto_basic_enum_proto_rawDesc
)

func file_proto_basic_enum_proto_rawDescGZIP() []byte {
	file_proto_basic_enum_proto_rawDescOnce.Do(func() {
		file_proto_basic_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_basic_enum_proto_rawDescData)
	})
	return file_proto_basic_enum_proto_rawDescData
}

var file_proto_basic_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_basic_enum_proto_goTypes = []any{
	(DbBool)(0),      // 0: basic.DbBool
	(DateSpan)(0),    // 1: basic.DateSpan
	(CombineKind)(0), // 2: basic.CombineKind
	(Language)(0),    // 3: basic.Language
}
var file_proto_basic_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_basic_enum_proto_init() }
func file_proto_basic_enum_proto_init() {
	if File_proto_basic_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_basic_enum_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_basic_enum_proto_goTypes,
		DependencyIndexes: file_proto_basic_enum_proto_depIdxs,
		EnumInfos:         file_proto_basic_enum_proto_enumTypes,
	}.Build()
	File_proto_basic_enum_proto = out.File
	file_proto_basic_enum_proto_rawDesc = nil
	file_proto_basic_enum_proto_goTypes = nil
	file_proto_basic_enum_proto_depIdxs = nil
}
