// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v5.29.1
// source: proto/hello/model.proto

package hello

import (
	_ "myproject/internal/proto/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Status        UserStatus             `protobuf:"varint,3,opt,name=Status,proto3,enum=hello.UserStatus" json:"Status,omitempty"`
	CreateTime    int64                  `protobuf:"varint,4,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_proto_hello_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_proto_hello_model_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_UserStatus_Normal
}

func (x *UserInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type UserListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
	Items         []*UserInfo            `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListResponse) Reset() {
	*x = UserListResponse{}
	mi := &file_proto_hello_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResponse) ProtoMessage() {}

func (x *UserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResponse.ProtoReflect.Descriptor instead.
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return file_proto_hello_model_proto_rawDescGZIP(), []int{1}
}

func (x *UserListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *UserListResponse) GetItems() []*UserInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type TestLinkDto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户id
	UserId int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	// 根据UserId获取用户名
	// @gotags: link:"Field(DbName = sjzy_user_center, TableName = t_user, KeyName = id, KeyValue = UserId, FieldName = Name, Language = Language.Auto)"
	UserName string `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	// 枚举PlaneType的值
	PlaneTypeValue int32 `protobuf:"varint,3,opt,name=PlaneTypeValue,proto3" json:"PlaneTypeValue,omitempty"`
	// 枚举PlaneType的描述
	// @gotags: link:"Enum(Name = PlaneType, Value = PlaneTypeValue, Product = Basic, Language = Language.Auto)"
	PlaneTypeDesc string `protobuf:"bytes,4,opt,name=PlaneTypeDesc,proto3" json:"PlaneTypeDesc,omitempty"`
	// 普通文本
	Text string `protobuf:"bytes,5,opt,name=Text,proto3" json:"Text,omitempty"`
	// Text的英文版
	// @gotags: link:"Text(Key = Text, Product = Basic, Language = Language.EnUs)"
	EnText        string `protobuf:"bytes,6,opt,name=EnText,proto3" json:"EnText,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestLinkDto) Reset() {
	*x = TestLinkDto{}
	mi := &file_proto_hello_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestLinkDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestLinkDto) ProtoMessage() {}

func (x *TestLinkDto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestLinkDto.ProtoReflect.Descriptor instead.
func (*TestLinkDto) Descriptor() ([]byte, []int) {
	return file_proto_hello_model_proto_rawDescGZIP(), []int{2}
}

func (x *TestLinkDto) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TestLinkDto) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *TestLinkDto) GetPlaneTypeValue() int32 {
	if x != nil {
		return x.PlaneTypeValue
	}
	return 0
}

func (x *TestLinkDto) GetPlaneTypeDesc() string {
	if x != nil {
		return x.PlaneTypeDesc
	}
	return ""
}

func (x *TestLinkDto) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TestLinkDto) GetEnText() string {
	if x != nil {
		return x.EnText
	}
	return ""
}

var File_proto_hello_model_proto protoreflect.FileDescriptor

var file_proto_hello_model_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x1a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2f, 0x65, 0x6e,
	0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x82, 0x01, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x29, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x11, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x4f, 0x0a, 0x10,
	0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x25, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xbb, 0x01,
	0x0a, 0x0b, 0x54, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x44, 0x74, 0x6f, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x26, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x50, 0x6c, 0x61, 0x6e, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x50, 0x6c, 0x61,
	0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x44, 0x65, 0x73, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x44, 0x65, 0x73, 0x63, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54,
	0x65, 0x78, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x45, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x42, 0x23, 0x5a, 0x0f, 0x62,
	0x73, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0xaa, 0x02,
	0x0f, 0x42, 0x53, 0x49, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_hello_model_proto_rawDescOnce sync.Once
	file_proto_hello_model_proto_rawDescData = file_proto_hello_model_proto_rawDesc
)

func file_proto_hello_model_proto_rawDescGZIP() []byte {
	file_proto_hello_model_proto_rawDescOnce.Do(func() {
		file_proto_hello_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_hello_model_proto_rawDescData)
	})
	return file_proto_hello_model_proto_rawDescData
}

var file_proto_hello_model_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_hello_model_proto_goTypes = []any{
	(*UserInfo)(nil),         // 0: hello.UserInfo
	(*UserListResponse)(nil), // 1: hello.UserListResponse
	(*TestLinkDto)(nil),      // 2: hello.TestLinkDto
	(UserStatus)(0),          // 3: hello.UserStatus
}
var file_proto_hello_model_proto_depIdxs = []int32{
	3, // 0: hello.UserInfo.Status:type_name -> hello.UserStatus
	0, // 1: hello.UserListResponse.Items:type_name -> hello.UserInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_hello_model_proto_init() }
func file_proto_hello_model_proto_init() {
	if File_proto_hello_model_proto != nil {
		return
	}
	file_proto_hello_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_hello_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_hello_model_proto_goTypes,
		DependencyIndexes: file_proto_hello_model_proto_depIdxs,
		MessageInfos:      file_proto_hello_model_proto_msgTypes,
	}.Build()
	File_proto_hello_model_proto = out.File
	file_proto_hello_model_proto_rawDesc = nil
	file_proto_hello_model_proto_goTypes = nil
	file_proto_hello_model_proto_depIdxs = nil
}
