basePath: /api/v1
definitions:
  models.ErrorResponse:
    description: 通用错误响应
    properties:
      error:
        example: Something went wrong
        type: string
    type: object
  models.Todo:
    description: Todo 项目模型
    properties:
      created_at:
        type: string
      done:
        description: Whether the todo is completed
        example: false
        type: boolean
      id:
        description: |-
          ID of the todo item
          in: path
          required: true
          example: 1
        example: 1
        type: integer
      title:
        description: |-
          Title of the todo
          required: true
          min length: 1
          max length: 50
        example: Learn Go
        type: string
      updated_at:
        type: string
    required:
    - title
    type: object
host: localhost:8082
info:
  contact: {}
  description: This is a sample server for a Todo List API.
  title: Sample API
  version: "1.0"
paths:
  /todos:
    get:
      description: 获取所有待办事项的列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Todo'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: 获取所有待办事项
      tags:
      - todos
    post:
      consumes:
      - application/json
      description: 创建一个新的待办事项
      parameters:
      - description: Todo 项目（无需传 ID）
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/models.Todo'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Todo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: 创建一个新的 Todo 项目
      tags:
      - todos
  /todos/{id}:
    get:
      description: 根据提供的 ID 获取一个具体的待办事项
      parameters:
      - description: 待办事项 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Todo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: 根据 ID 获取单个待办事项
      tags:
      - todos
swagger: "2.0"
